Gtk4/Scales: fix mark selector
elementary/stylesheet pull request #1221
Opened 2022-08-15 20:59 UTC by danrabbit

Fixes #1219

It looks like vertical scale marks are always on the right, even in RTL so we don't need to account for that

2022-08-18 02:11 UTC, lenemter requested changes
Vertical scale marks are not always on the right, because you can specify their position in add_mark method.
Marks on the left have no margin

![image](https://user-images.githubusercontent.com/80143868/185276627-29bc2d25-6c80-46fd-a7a6-341e0166be2b.png)

2022-08-18 17:59 UTC, danrabbit commented
Ah sorry you're absolutely right. Thanks for the attention to detail!

2022-08-19 19:04 UTC, danrabbit commented
@lenemter should be fixed now

2022-08-20 03:09 UTC, lenemter approved these changes
Fixes the issue now. Thanks

2022-08-21 16:43 UTC, merged

2022-08-21 16:44 UTC, danrabbit commented
Thanks for reviewing!