Notebooks: Support all positions
elementary/stylesheet pull request #832
Opened 2020-09-15 22:35 UTC by danrabbit

Fixes #828 

![Screenshot from 2020-09-15 15 34 02@2x](https://user-images.githubusercontent.com/7277719/93271815-fd817280-f768-11ea-8d3f-d0e2c9ba31de.png)

2020-10-01 03:36 UTC, cassidyjames commented on src/widgets/_notebooks.scss
> +        }
Can we DRY this out a bit?

```suggestion
        $gradient: 
            rgba(black, 0),
            rgba(black, 0) calc(100% - #{rem(2px)}),
            rgba(black, 0.05) calc(100% - #{rem(1px)}),
            rgba(black, 0.15);

        &.top {
            background-image: linear-gradient(to bottom, $gradient);
        }

        &.bottom {
            background-image: linear-gradient(to top, $gradient);
        }

        &.right {
            background-image: linear-gradient(to left, $gradient);
        }

        &.left {
            background-image: linear-gradient(to right, $gradient);
        }
```

2020-10-01 03:37 UTC, cassidyjames requested changes
DRY

2020-10-01 04:05 UTC, danrabbit commented
Ah yes. Im still thinking in CSS sometimes

2020-10-12 22:03 UTC, cassidyjames approved these changes
Nice

2020-10-12 22:04 UTC, merged